





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Linq;

using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Configuration.Attributes;

using Sitecore.ContentSearch;
using Sitecore.ContentSearch.Converters;
using Sitecore.Data;
using Sitecore.Globalization;
using System.Web;


namespace MySitecoreApplication
{

    public interface IGlassBase
    {
        [SitecoreId]
        Guid EntityId{ get; }

        [SitecoreInfo(SitecoreInfoType.Language)]
        Language EntityLanguage{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int EntityVersion { get; }

        [SitecoreInfo(SitecoreInfoType.ContentPath)]
        string EntityContentPath { get; }

        [SitecoreInfo(SitecoreInfoType.Name)]
        string EntityName { get; }

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        string EntityDisplayName{ get; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid EntityTemplateId { get; }
    }

    public abstract class GlassBase : IGlassBase
    {
        [SitecoreId]
        [TypeConverter(typeof(IndexFieldGuidValueConverter))]
        [IndexField("_group")]
        public virtual Guid EntityId{ get; set;}

        [TypeConverter(typeof(IndexFieldLanguageValueConverter))]
        [SitecoreInfo(SitecoreInfoType.Language)]
        [IndexField("_language")]
        public virtual Language EntityLanguage{ get; set; }

        [SitecoreIgnore]
        [TypeConverter(typeof(IndexFieldItemUriValueConverter))]
        [IndexField("_uniqueid")]
        public virtual ItemUri EntityUri { get; set; }

        [TypeConverter(typeof(IndexFieldGuidValueConverter))]
        [IndexField("_parent")]
        [SitecoreIgnore]
        public virtual Guid EntityParent { get; set; }

        [IndexField("_path"), TypeConverter(typeof(IndexFieldEnumerableConverter))]
        [SitecoreIgnore]
        public virtual System.Collections.Generic.IEnumerable<Guid> EntityPath { get; set; }

        [SitecoreInfo(SitecoreInfoType.ContentPath)]
        public virtual string EntityContentPath { get; set; }

        [SitecoreInfo(SitecoreInfoType.Name)]
        [IndexField("_name")]
        public virtual string EntityName { get; set; }

        [SitecoreInfo(SitecoreInfoType.DisplayName)]
        public virtual string EntityDisplayName{ get; set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int EntityMappedVersion { get; set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int EntityVersion
        {
                get
                {
                    return EntityUri == null ? EntityMappedVersion : EntityUri.Version.Number;
                }
        }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        [TypeConverter(typeof(IndexFieldGuidValueConverter))]
        [IndexField("_template")]
        public virtual Guid EntityTemplateId { get; set; }

        /// <summary>
        /// Gets or set sort able publish date as stored in the index.
        /// This value will be populated by Sitecore Lucene provider from the index.
        /// Used to help index queries. Will be empty if the entity was not read from index.
        /// </summary>
        [SitecoreIgnore]
        [IndexField("_bupa_publishdate")]
        public string PublishDateIndexValue { get; set; }
		
		#region BUPA Additions
		/// <summary>
        /// Constructs parameter for FieldRenderer.Render
        /// </summary>
        /// <param name="isEditable"></param>
        /// <param name="parameters"></param>
        /// <returns></returns>
		public static string GenerateRenderParameter(bool isEditable, string parameters)
			{
				string renderParameter;
				if (!isEditable)
				{
					if (string.IsNullOrEmpty(parameters))
					{
						renderParameter = "disable-web-editing=true";
					}
					else
					{
						renderParameter = "disable-web-editing=true&" + parameters;
					}
				}
				else
				{
					renderParameter = parameters;
				}
				return renderParameter;
			}	
		[SitecoreInfo(SitecoreInfoType.Url)]
        public string Url { get; set; }

		#endregion BUPA Additions
    }
}
namespace MySitecoreApplication.UserDefined.HomeData
{


    /// <summary>
    /// IHomeData Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/HomeData</para>
    /// <para>ID: 0ad8a0b7-97e6-4155-b63d-945c043cb3a3</para>
    /// </summary>
    [SitecoreType(TemplateId=IHomeDataConstants.TemplateIdString )] //, Cachable = true
    public partial interface IHomeData : IGlassBase 
    {
                                /// <summary>
                    /// The _firstName field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: e567acb3-a804-4bd7-ba86-d8ccccc2bb7b</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IHomeDataConstants._FirstNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    string _FirstName  {get; set;}
            
                                /// <summary>
                    /// The _homeUrl field.
                    /// <para></para>
                    /// <para>Field Type: General Link</para>
                    /// <para>Field ID: 24b4df95-60d7-4224-9b8e-c0b432eabf3a</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IHomeDataConstants._HomeUrlFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    Glass.Mapper.Sc.Fields.Link _HomeUrl  {get; set;}
            
                                /// <summary>
                    /// The _lastName field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: c4f1cb9d-8e10-47f0-87a0-c428267c01d1</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IHomeDataConstants._LastNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    string _LastName  {get; set;}
            
                }


    public static partial class IHomeDataConstants{
            public const string TemplateIdString = "0ad8a0b7-97e6-4155-b63d-945c043cb3a3";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "HomeData";

                    
            public static readonly ID _FirstNameFieldId = new ID("e567acb3-a804-4bd7-ba86-d8ccccc2bb7b");
            public const string _FirstNameFieldName = "_firstName";
                    
            public static readonly ID _HomeUrlFieldId = new ID("24b4df95-60d7-4224-9b8e-c0b432eabf3a");
            public const string _HomeUrlFieldName = "_homeUrl";
                    
            public static readonly ID _LastNameFieldId = new ID("c4f1cb9d-8e10-47f0-87a0-c428267c01d1");
            public const string _LastNameFieldName = "_lastName";
            }

	
    /// <summary>
    /// HomeData
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/HomeData</para>
    /// <para>ID: 0ad8a0b7-97e6-4155-b63d-945c043cb3a3</para>
    /// </summary>
    [SitecoreType(TemplateId=IHomeDataConstants.TemplateIdString)] //, Cachable = true
    public partial class HomeDataEntity  : GlassBase, IHomeData 
    {
                        /// <summary>
                /// The _firstName field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: e567acb3-a804-4bd7-ba86-d8ccccc2bb7b</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("_firstname")]
                [SitecoreField(IHomeDataConstants._FirstNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string _FirstName  {get; set;}
				//BUPA
				public HtmlString _FirstNameField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "_firstName", renderParameter ));
				}
                        /// <summary>
                /// The _homeUrl field.
                /// <para></para>
                /// <para>Field Type: General Link</para>
                /// <para>Field ID: 24b4df95-60d7-4224-9b8e-c0b432eabf3a</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("_homeurl")]
                [SitecoreField(IHomeDataConstants._HomeUrlFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual Glass.Mapper.Sc.Fields.Link _HomeUrl  {get; set;}
				//BUPA
				public HtmlString _HomeUrlField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "_homeUrl", renderParameter ));
				}
                        /// <summary>
                /// The _lastName field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: c4f1cb9d-8e10-47f0-87a0-c428267c01d1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("_lastname")]
                [SitecoreField(IHomeDataConstants._LastNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string _LastName  {get; set;}
				//BUPA
				public HtmlString _LastNameField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "_lastName", renderParameter ));
				}
            }
}
namespace MySitecoreApplication.Constants
{
    public static partial class Entities{
       public static partial class Layout{
          public static partial class Layouts{
            /// <summary>
            /// MasterLayout Item
            /// <para></para>
            /// <para>Path: /sitecore/layout/Layouts/MasterLayout</para>
            /// <para>ID: 0d51d8c2-46b9-443b-b886-f293c294d8a6</para>
            /// </summary>
            public static partial class MasterLayout{
                public const string ID = "0d51d8c2-46b9-443b-b886-f293c294d8a6";
                public const string Name = "MasterLayout";
                public const string Path = "/sitecore/layout/Layouts/MasterLayout";
                public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID(ID); } }
            
                public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("3a45a723-64ee-4919-9d41-02fd40fd1466"); } }
                public const string TemplateName = "Layout";
            }
          }
       }
    }
}
namespace MySitecoreApplication.Constants
{
    public static partial class Entities{
       public static partial class Layout{
          public static partial class Renderings{
            /// <summary>
            /// DasboardPage Item
            /// <para></para>
            /// <para>Path: /sitecore/layout/Renderings/DasboardPage</para>
            /// <para>ID: 1b9386d2-9e48-48d8-ba5f-f7e1ca125035</para>
            /// </summary>
            public static partial class DasboardPage{
                public const string ID = "1b9386d2-9e48-48d8-ba5f-f7e1ca125035";
                public const string Name = "DasboardPage";
                public const string Path = "/sitecore/layout/Renderings/DasboardPage";
                public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID(ID); } }
            
                public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("2a3e91a0-7987-44b5-ab34-35c2d9de83b9"); } }
                public const string TemplateName = "Controller rendering";
            }
          }
       }
    }
}
namespace MySitecoreApplication.UserDefined.DogData
{


    /// <summary>
    /// IDogData Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/DogData</para>
    /// <para>ID: 1dd1ac58-b311-4501-8e1d-c4fac5074476</para>
    /// </summary>
    [SitecoreType(TemplateId=IDogDataConstants.TemplateIdString )] //, Cachable = true
    public partial interface IDogData : IGlassBase 
    {
                                /// <summary>
                    /// The Description field.
                    /// <para></para>
                    /// <para>Field Type: Multi-Line Text</para>
                    /// <para>Field ID: 734023b1-6d10-4686-91da-985380f81a2d</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IDogDataConstants.DescriptionFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    string Description  {get; set;}
            
                                /// <summary>
                    /// The Image field.
                    /// <para></para>
                    /// <para>Field Type: Image</para>
                    /// <para>Field ID: 3f864b2a-215e-4833-8869-557b1aa1d557</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IDogDataConstants.ImageFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    Glass.Mapper.Sc.Fields.Image Image  {get; set;}
            
                                /// <summary>
                    /// The Title field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: 5aab67ca-9f7a-491e-972e-d29cb3b58ed2</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IDogDataConstants.TitleFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    string Title  {get; set;}
            
                }


    public static partial class IDogDataConstants{
            public const string TemplateIdString = "1dd1ac58-b311-4501-8e1d-c4fac5074476";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "DogData";

                    
            public static readonly ID DescriptionFieldId = new ID("734023b1-6d10-4686-91da-985380f81a2d");
            public const string DescriptionFieldName = "Description";
                    
            public static readonly ID ImageFieldId = new ID("3f864b2a-215e-4833-8869-557b1aa1d557");
            public const string ImageFieldName = "Image";
                    
            public static readonly ID TitleFieldId = new ID("5aab67ca-9f7a-491e-972e-d29cb3b58ed2");
            public const string TitleFieldName = "Title";
            }

	
    /// <summary>
    /// DogData
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/DogData</para>
    /// <para>ID: 1dd1ac58-b311-4501-8e1d-c4fac5074476</para>
    /// </summary>
    [SitecoreType(TemplateId=IDogDataConstants.TemplateIdString)] //, Cachable = true
    public partial class DogDataEntity  : GlassBase, IDogData 
    {
                        /// <summary>
                /// The Description field.
                /// <para></para>
                /// <para>Field Type: Multi-Line Text</para>
                /// <para>Field ID: 734023b1-6d10-4686-91da-985380f81a2d</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("description")]
                [SitecoreField(IDogDataConstants.DescriptionFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string Description  {get; set;}
				//BUPA
				public HtmlString DescriptionField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "Description", renderParameter ));
				}
                        /// <summary>
                /// The Image field.
                /// <para></para>
                /// <para>Field Type: Image</para>
                /// <para>Field ID: 3f864b2a-215e-4833-8869-557b1aa1d557</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("image")]
                [SitecoreField(IDogDataConstants.ImageFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual Glass.Mapper.Sc.Fields.Image Image  {get; set;}
				//BUPA
				public HtmlString ImageField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "Image", renderParameter ));
				}
                        /// <summary>
                /// The Title field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 5aab67ca-9f7a-491e-972e-d29cb3b58ed2</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("title")]
                [SitecoreField(IDogDataConstants.TitleFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string Title  {get; set;}
				//BUPA
				public HtmlString TitleField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "Title", renderParameter ));
				}
            }
}
namespace MySitecoreApplication.Constants
{
    public static partial class Entities{
       public static partial class Layout{
         /// <summary>
         /// Renderings Item
         /// <para>レンダリング</para>
         /// <para>Path: /sitecore/layout/Renderings</para>
         /// <para>ID: 32566f0e-7686-45f1-a12f-d7260bd78bc3</para>
         /// </summary>
         public static partial class Renderings{
             public const string ID = "32566f0e-7686-45f1-a12f-d7260bd78bc3";
             public const string Name = "Renderings";
             public const string Path = "/sitecore/layout/Renderings";
             public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID(ID); } }
         
             public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("239f9cf4-e5a0-44e0-b342-0f32cd4c6d8b"); } }
             public const string TemplateName = "Node";
         }
       }
    }
}
namespace MySitecoreApplication.Constants
{
    public static partial class Entities{
       public static partial class Layout{
         /// <summary>
         /// Layouts Item
         /// <para>レイアウト</para>
         /// <para>Path: /sitecore/layout/Layouts</para>
         /// <para>ID: 75cc5ce4-8979-4008-9d3c-806477d57619</para>
         /// </summary>
         public static partial class Layouts{
             public const string ID = "75cc5ce4-8979-4008-9d3c-806477d57619";
             public const string Name = "Layouts";
             public const string Path = "/sitecore/layout/Layouts";
             public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID(ID); } }
         
             public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("239f9cf4-e5a0-44e0-b342-0f32cd4c6d8b"); } }
             public const string TemplateName = "Node";
         }
       }
    }
}
namespace MySitecoreApplication.UserDefined.CustomerData
{


    /// <summary>
    /// ICustomerData Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/CustomerData</para>
    /// <para>ID: 7848eabb-470e-4ac6-8feb-b2bfb8675b5c</para>
    /// </summary>
    [SitecoreType(TemplateId=ICustomerDataConstants.TemplateIdString )] //, Cachable = true
    public partial interface ICustomerData : IGlassBase 
    {
                                /// <summary>
                    /// The _address field.
                    /// <para></para>
                    /// <para>Field Type: Multi-Line Text</para>
                    /// <para>Field ID: 971b8cb4-97b5-427a-862d-5545a07eb0e5</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ICustomerDataConstants._AddressFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    string _Address  {get; set;}
            
                                /// <summary>
                    /// The _FirstName field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: f6bdb38e-6d5e-4a5f-9664-be11535ded52</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ICustomerDataConstants._FirstNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    string _FirstName  {get; set;}
            
                                /// <summary>
                    /// The _LastName field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: c887bba1-a20e-4f58-b406-04dec9927f5f</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(ICustomerDataConstants._LastNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    string _LastName  {get; set;}
            
                }


    public static partial class ICustomerDataConstants{
            public const string TemplateIdString = "7848eabb-470e-4ac6-8feb-b2bfb8675b5c";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "CustomerData";

                    
            public static readonly ID _AddressFieldId = new ID("971b8cb4-97b5-427a-862d-5545a07eb0e5");
            public const string _AddressFieldName = "_address";
                    
            public static readonly ID _FirstNameFieldId = new ID("f6bdb38e-6d5e-4a5f-9664-be11535ded52");
            public const string _FirstNameFieldName = "_FirstName";
                    
            public static readonly ID _LastNameFieldId = new ID("c887bba1-a20e-4f58-b406-04dec9927f5f");
            public const string _LastNameFieldName = "_LastName";
            }

	
    /// <summary>
    /// CustomerData
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/CustomerData</para>
    /// <para>ID: 7848eabb-470e-4ac6-8feb-b2bfb8675b5c</para>
    /// </summary>
    [SitecoreType(TemplateId=ICustomerDataConstants.TemplateIdString)] //, Cachable = true
    public partial class CustomerDataEntity  : GlassBase, ICustomerData 
    {
                        /// <summary>
                /// The _address field.
                /// <para></para>
                /// <para>Field Type: Multi-Line Text</para>
                /// <para>Field ID: 971b8cb4-97b5-427a-862d-5545a07eb0e5</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("_address")]
                [SitecoreField(ICustomerDataConstants._AddressFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string _Address  {get; set;}
				//BUPA
				public HtmlString _AddressField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "_address", renderParameter ));
				}
                        /// <summary>
                /// The _FirstName field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: f6bdb38e-6d5e-4a5f-9664-be11535ded52</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("_firstname")]
                [SitecoreField(ICustomerDataConstants._FirstNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string _FirstName  {get; set;}
				//BUPA
				public HtmlString _FirstNameField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "_FirstName", renderParameter ));
				}
                        /// <summary>
                /// The _LastName field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: c887bba1-a20e-4f58-b406-04dec9927f5f</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("_lastname")]
                [SitecoreField(ICustomerDataConstants._LastNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string _LastName  {get; set;}
				//BUPA
				public HtmlString _LastNameField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "_LastName", renderParameter ));
				}
            }
}
namespace MySitecoreApplication.UserDefined.HeaderData
{


    /// <summary>
    /// IHeaderData Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/HeaderData</para>
    /// <para>ID: 940cd4c5-45f5-4007-be3c-7b5e37bec77c</para>
    /// </summary>
    [SitecoreType(TemplateId=IHeaderDataConstants.TemplateIdString )] //, Cachable = true
    public partial interface IHeaderData : IGlassBase 
    {
                                /// <summary>
                    /// The headerName field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: d853e051-b808-48bd-ad0f-2fa568e5ed86</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IHeaderDataConstants.HeaderNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    string HeaderName  {get; set;}
            
                }


    public static partial class IHeaderDataConstants{
            public const string TemplateIdString = "940cd4c5-45f5-4007-be3c-7b5e37bec77c";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "HeaderData";

                    
            public static readonly ID HeaderNameFieldId = new ID("d853e051-b808-48bd-ad0f-2fa568e5ed86");
            public const string HeaderNameFieldName = "headerName";
            }

	
    /// <summary>
    /// HeaderData
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/HeaderData</para>
    /// <para>ID: 940cd4c5-45f5-4007-be3c-7b5e37bec77c</para>
    /// </summary>
    [SitecoreType(TemplateId=IHeaderDataConstants.TemplateIdString)] //, Cachable = true
    public partial class HeaderDataEntity  : GlassBase, IHeaderData 
    {
                        /// <summary>
                /// The headerName field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: d853e051-b808-48bd-ad0f-2fa568e5ed86</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("headername")]
                [SitecoreField(IHeaderDataConstants.HeaderNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string HeaderName  {get; set;}
				//BUPA
				public HtmlString HeaderNameField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "headerName", renderParameter ));
				}
            }
}
namespace MySitecoreApplication.UserDefined.FooterData
{


    /// <summary>
    /// IFooterData Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/FooterData</para>
    /// <para>ID: a8c57642-5fd0-4e7f-98ea-84354d1728d3</para>
    /// </summary>
    [SitecoreType(TemplateId=IFooterDataConstants.TemplateIdString )] //, Cachable = true
    public partial interface IFooterData : IGlassBase 
    {
                                /// <summary>
                    /// The footerName field.
                    /// <para></para>
                    /// <para>Field Type: Single-Line Text</para>
                    /// <para>Field ID: 8698f7d2-1a2b-4758-926e-a27b579a8f70</para>
                    /// <para>Custom Data: </para>
                    /// </summary>
                    [SitecoreField(IFooterDataConstants.FooterNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                    string FooterName  {get; set;}
            
                }


    public static partial class IFooterDataConstants{
            public const string TemplateIdString = "a8c57642-5fd0-4e7f-98ea-84354d1728d3";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "FooterData";

                    
            public static readonly ID FooterNameFieldId = new ID("8698f7d2-1a2b-4758-926e-a27b579a8f70");
            public const string FooterNameFieldName = "footerName";
            }

	
    /// <summary>
    /// FooterData
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/FooterData</para>
    /// <para>ID: a8c57642-5fd0-4e7f-98ea-84354d1728d3</para>
    /// </summary>
    [SitecoreType(TemplateId=IFooterDataConstants.TemplateIdString)] //, Cachable = true
    public partial class FooterDataEntity  : GlassBase, IFooterData 
    {
                        /// <summary>
                /// The footerName field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: 8698f7d2-1a2b-4758-926e-a27b579a8f70</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("footername")]
                [SitecoreField(IFooterDataConstants.FooterNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string FooterName  {get; set;}
				//BUPA
				public HtmlString FooterNameField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "footerName", renderParameter ));
				}
            }
}
namespace MySitecoreApplication.Constants
{
    public static partial class Entities{
       public static partial class Content{
         /// <summary>
         /// Global Data Item
         /// <para></para>
         /// <para>Path: /sitecore/content/Global Data</para>
         /// <para>ID: c172593e-f42d-4f7d-b5fa-91c9b11121eb</para>
         /// </summary>
         public static partial class GlobalData{
             public const string ID = "c172593e-f42d-4f7d-b5fa-91c9b11121eb";
             public const string Name = "Global Data";
             public const string Path = "/sitecore/content/Global Data";
             public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID(ID); } }
         
             public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("a87a00b1-e6db-45ab-8b54-636fec3b5523"); } }
             public const string TemplateName = "Folder";
         }
       }
    }
}
namespace MySitecoreApplication.Constants
{
    public static partial class Entities{
       public static partial class Content{
         /// <summary>
         /// Dashboard Item
         /// <para></para>
         /// <para>Path: /sitecore/content/Dashboard</para>
         /// <para>ID: d698f199-0a1e-4fbd-a937-bbc59c4c2c7f</para>
         /// </summary>
         public static partial class Dashboard{
             public const string ID = "d698f199-0a1e-4fbd-a937-bbc59c4c2c7f";
             public const string Name = "Dashboard";
             public const string Path = "/sitecore/content/Dashboard";
             public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID(ID); } }
         
             public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("e697c759-edb7-4c73-94be-81f349ee721b"); } }
             public const string TemplateName = "HomePage";
         }
       }
    }
}
namespace MySitecoreApplication.Constants
{
    public static partial class Entities{
       public static partial class Content{
          public static partial class GlobalData{
            /// <summary>
            /// SuperCustomer Item
            /// <para></para>
            /// <para>Path: /sitecore/content/Global Data/SuperCustomer</para>
            /// <para>ID: e1595f1a-b4c4-46c1-949c-b8ebf9ba4d38</para>
            /// </summary>
            public static partial class SuperCustomer{
                public const string ID = "e1595f1a-b4c4-46c1-949c-b8ebf9ba4d38";
                public const string Name = "SuperCustomer";
                public const string Path = "/sitecore/content/Global Data/SuperCustomer";
                public static global::Sitecore.Data.ID ItemID { get { return new global::Sitecore.Data.ID(ID); } }
            
                public static global::Sitecore.Data.ID TemplateID { get { return  new global::Sitecore.Data.ID("7848eabb-470e-4ac6-8feb-b2bfb8675b5c"); } }
                public const string TemplateName = "CustomerData";
            }
          }
       }
    }
}
namespace MySitecoreApplication.UserDefined.HomePage
{


    /// <summary>
    /// IHomePage Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/HomePage</para>
    /// <para>ID: e697c759-edb7-4c73-94be-81f349ee721b</para>
    /// </summary>
    [SitecoreType(TemplateId=IHomePageConstants.TemplateIdString )] //, Cachable = true
    public partial interface IHomePage : IGlassBase , global::MySitecoreApplication.UserDefined.HomeData.IHomeData
    {
                }


    public static partial class IHomePageConstants{
            public const string TemplateIdString = "e697c759-edb7-4c73-94be-81f349ee721b";
            public static readonly ID TemplateId = new ID(TemplateIdString);
            public const string TemplateName = "HomePage";

                    
            public static readonly ID _FirstNameFieldId = new ID("e567acb3-a804-4bd7-ba86-d8ccccc2bb7b");
            public const string _FirstNameFieldName = "_firstName";
                    
            public static readonly ID _HomeUrlFieldId = new ID("24b4df95-60d7-4224-9b8e-c0b432eabf3a");
            public const string _HomeUrlFieldName = "_homeUrl";
                    
            public static readonly ID _LastNameFieldId = new ID("c4f1cb9d-8e10-47f0-87a0-c428267c01d1");
            public const string _LastNameFieldName = "_lastName";
            }

	
    /// <summary>
    /// HomePage
    /// <para></para>
    /// <para>Path: /sitecore/templates/User Defined/HomePage</para>
    /// <para>ID: e697c759-edb7-4c73-94be-81f349ee721b</para>
    /// </summary>
    [SitecoreType(TemplateId=IHomePageConstants.TemplateIdString)] //, Cachable = true
    public partial class HomePageEntity  : GlassBase, IHomePage 
    {
                        /// <summary>
                /// The _firstName field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: e567acb3-a804-4bd7-ba86-d8ccccc2bb7b</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("_firstname")]
                [SitecoreField(IHomePageConstants._FirstNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string _FirstName  {get; set;}
				//BUPA
				public HtmlString _FirstNameField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "_firstName", renderParameter ));
				}
                        /// <summary>
                /// The _homeUrl field.
                /// <para></para>
                /// <para>Field Type: General Link</para>
                /// <para>Field ID: 24b4df95-60d7-4224-9b8e-c0b432eabf3a</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("_homeurl")]
                [SitecoreField(IHomePageConstants._HomeUrlFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual Glass.Mapper.Sc.Fields.Link _HomeUrl  {get; set;}
				//BUPA
				public HtmlString _HomeUrlField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "_homeUrl", renderParameter ));
				}
                        /// <summary>
                /// The _lastName field.
                /// <para></para>
                /// <para>Field Type: Single-Line Text</para>
                /// <para>Field ID: c4f1cb9d-8e10-47f0-87a0-c428267c01d1</para>
                /// <para>Custom Data: </para>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
                [IndexField("_lastname")]
                [SitecoreField(IHomePageConstants._LastNameFieldName, Setting = SitecoreFieldSettings.RichTextRaw)]
                public virtual string _LastName  {get; set;}
				//BUPA
				public HtmlString _LastNameField(bool isEditable = true, string parameters = "")
				{ 
					string renderParameter = GenerateRenderParameter(isEditable, parameters);

					return new HtmlString(Sitecore.Web.UI.WebControls.FieldRenderer.Render(
						Sitecore.Context.Database.GetItem(this.EntityId.ToString()), "_lastName", renderParameter ));
				}
            }
}
